---
 - hosts: default
   sudo: yes
   vars:
     ruby_version: ruby2.0
     rails_postgresql_db_name: seatpicker

   roles:
     - ShadowKoBolt.core
     - ShadowKoBolt.rails-common

   tasks:
    - name: rails install
      command: gem install rails

    - name: bundle install
      remote_user: vagrant 
      sudo: no
      command: bundle install chdir=/home/vagrant/source

    - name: pry install
      command: gem install pry
