---
 - hosts: default
   sudo: yes
   vars:
     ruby_version: ruby2.0
     rails_postgresql_db_name: seatpicker 
     postgres_version: 9.1
     distro: ubuntu

   roles:
     - ShadowKoBolt.core
     - ShadowKoBolt.rails-common

   tasks:
    - name: rails install
      command: gem install rails

    - name: bundle install
      remote_user: vagrant 
      sudo: no
      command: bundle install chdir=/home/vagrant/source

    - name: pry install
      command: gem install pry

    # seeding currently fails with a bundler exception
    # - name: create database
    #   command: bundle exec rake db:create && rake db:migrate && rake db:seed chdir=/home/vagrant/source
