---
  - name: install postgresql packages
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - postgresql-9.1
      - postgresql-client-9.1
      - postgresql-contrib-9.1
      - libpq-dev
      - python-psycopg2
