---
  - name: install some dependencies for some gems
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - imagemagick
      - libproj-dev
      - libxml2-dev
      - libxslt1-dev
      - sqlite3
      - libsqlite3-dev
      - libzmq-dev
      - libaspell-dev
